# Generated by Django 4.2.2 on 2023-06-26 07:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('station_app', '0002_register_dgp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='register_dgp',
            name='office_address',
            field=models.TextField(),
        ),
        migrations.CreateModel(
            name='Register_station',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('station_name', models.CharField(max_length=50)),
                ('phone', models.CharField(max_length=15)),
                ('office_address', models.TextField()),
                ('dgp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='station_app.register_dgp')),
                ('user_login', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
