# Generated by Django 4.2.2 on 2023-06-26 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('station_app', '0003_alter_register_dgp_office_address_register_station'),
    ]

    operations = [
        migrations.AddField(
            model_name='register_dgp',
            name='email',
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='register_station',
            name='email',
            field=models.EmailField(max_length=254, null=True),
        ),
    ]
