# Generated by Django 4.2.2 on 2023-06-26 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('station_app', '0005_register_wanted'),
    ]

    operations = [
        migrations.AddField(
            model_name='register_wanted',
            name='fname',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='register_wanted',
            name='lname',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
