# Generated by Django 4.2.2 on 2023-06-26 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('station_app', '0006_register_wanted_fname_register_wanted_lname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='register_wanted',
            name='wanted_images',
            field=models.ImageField(upload_to=''),
        ),
    ]
