# Generated by Django 4.2.2 on 2023-06-26 10:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('station_app', '0008_remove_register_wanted_wanted_images_wanted_images'),
    ]

    operations = [
        migrations.AddField(
            model_name='register_wanted',
            name='address',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='register_wanted',
            name='age',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='register_wanted',
            name='crime_desc',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='register_wanted',
            name='date_of_arrest',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='register_wanted',
            name='dgp',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='station_app.register_dgp'),
        ),
        migrations.AddField(
            model_name='register_wanted',
            name='father_name',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='register_wanted',
            name='mode_of_crime',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='register_wanted',
            name='sex',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
