# Generated by Django 4.2.2 on 2023-06-26 11:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('station_app', '0009_register_wanted_address_register_wanted_age_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='register_wanted',
            old_name='dgp',
            new_name='station',
        ),
    ]
