# Generated by Django 4.2.2 on 2023-06-26 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('station_app', '0012_register_public'),
    ]

    operations = [
        migrations.CreateModel(
            name='Add_complaint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('missing_date', models.DateField(blank=True)),
                ('missing_image', models.ImageField(blank=True, upload_to='')),
                ('missing_desc', models.TextField(blank=True)),
                ('crime_mode', models.CharField(blank=True, max_length=30)),
                ('crime_desc', models.TextField(blank=True)),
                ('crime_date', models.DateField(blank=True)),
                ('complaint_status', models.CharField(default='Pending', max_length=10)),
            ],
        ),
    ]
