# Generated by Django 4.2.2 on 2023-06-26 16:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('station_app', '0014_alter_add_complaint_crime_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='add_complaint',
            name='crime_date',
        ),
        migrations.RemoveField(
            model_name='add_complaint',
            name='missing_date',
        ),
    ]
