# Generated by Django 4.2.2 on 2023-06-26 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('station_app', '0015_remove_add_complaint_crime_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='add_complaint',
            name='complaintid',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
