# Generated by Django 4.2.2 on 2023-06-27 00:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('station_app', '0016_add_complaint_complaintid'),
    ]

    operations = [
        migrations.AddField(
            model_name='add_complaint',
            name='public',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='station_app.register_public'),
        ),
    ]
