# Generated by Django 4.2.2 on 2023-06-27 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('station_app', '0017_add_complaint_public'),
    ]

    operations = [
        migrations.AddField(
            model_name='register_public',
            name='district',
            field=models.CharField(max_length=15, null=True),
        ),
    ]
