# Generated by Django 4.2.2 on 2023-06-27 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('station_app', '0018_register_public_district'),
    ]

    operations = [
        migrations.AddField(
            model_name='add_complaint',
            name='complaint_type_status',
            field=models.CharField(default='missing', max_length=10),
        ),
    ]
