# Generated by Django 4.2.2 on 2023-06-28 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('station_app', '0019_add_complaint_complaint_type_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='add_complaint',
            name='complaint_date',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
