# Generated by Django 4.2.2 on 2023-06-28 04:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('station_app', '0020_add_complaint_complaint_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='register_wanted',
            name='date_of_arrest',
        ),
    ]
