# Generated by Django 4.2.2 on 2023-06-28 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('station_app', '0021_remove_register_wanted_date_of_arrest'),
    ]

    operations = [
        migrations.AddField(
            model_name='register_wanted',
            name='wanted_status',
            field=models.CharField(default='wanted', max_length=15),
        ),
    ]
