# Generated by Django 4.2.2 on 2023-06-28 08:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('station_app', '0022_register_wanted_wanted_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='add_complaint',
            name='criminal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='station_app.register_wanted'),
        ),
        migrations.AddField(
            model_name='add_complaint',
            name='station',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='station_app.register_station'),
        ),
    ]
