# Generated by Django 4.2.2 on 2023-06-29 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('station_app', '0025_public_feedback'),
    ]

    operations = [
        migrations.AddField(
            model_name='add_complaint',
            name='fir_upload',
            field=models.FileField(null=True, upload_to=''),
        ),
    ]
